<a href="https://colab.research.google.com/github/Anjinhyoung/TIL-Today-I-Learned-/blob/main/2_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Pandas
* 데이터 작업을 쉽고 직관적으로 할 수 있도록 설계된 빠르고 유연한 데이터 구조를 제공하는 모듈

In [ ]:
#!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
pd

### 1-1. Series와 DateFrame
* 1차원, 1개의 column을 Series라고 부름
* 데이터 프레임:가로축,세로축이 있는 2차원 다양한 타입의 데이터를 저장하는 자료구조

In [ ]:
pd.Series([1,2,3,4])
a=[1,2,3,4]
pd.Series(a)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
product1 = [['삼성',990000, '갤럭시23'],
            ['애플',1500000,'맥북에어'],
            ['엘지',600000,'공기청정기']]

In [ ]:
product1

[['삼성', 990000, '갤럭시23'], ['애플', 1500000, '맥북에어'], ['엘지', 600000, '공기청정기']]

In [ ]:
pd.DataFrame(product1)

    0        1      2
0  삼성   990000  갤럭시23
1  애플  1500000   맥북에어
2  엘지   600000  공기청정기

In [ ]:
df1 = pd.DataFrame(product1)

In [ ]:
df1

    0        1      2
0  삼성   990000  갤럭시23
1  애플  1500000   맥북에어
2  엘지   600000  공기청정기

In [ ]:
df1.columns = ['회사명','가격','상품명']

In [ ]:
df1

  회사명       가격    상품명
0  삼성   990000  갤럭시23
1  애플  1500000   맥북에어
2  엘지   600000  공기청정기

In [ ]:
# 딕셔너리를 통해 데이터프레임 만들기
product2 = {
    '회사명':['삼성','애플','엘지'],
    '가격':[990000,1500000,600000],
    '상품명':['갤럭시23','맥북에어','공기청정기']
}

In [ ]:
df2 = pd.DataFrame(product2)

In [ ]:
df2

  회사명       가격    상품명
0  삼성   990000  갤럭시23
1  애플  1500000   맥북에어
2  엘지   600000  공기청정기

In [ ]:
df2['상품명']

0    갤럭시23
1     맥북에어
2    공기청정기
Name: 상품명, dtype: object

In [ ]:
type(df2['상품명'])

pandas.core.series.Series